### ISSUE TITLE
Code window doesn't load

### ISSUE THREAD

**Issue by ilkerarslan** [datacamp/datacamp-light-wordpress#3]
Hi,

I am designing an education site with wordpress, for R and Python tutorials. The site uses learnpress and Datacamp Light plugins together. In the tutorials, the code editor doesn't load and the Datacamp icon with revolving sides continues to show up. 

Could you please give some idea about the reason of this? 

Many thanks in advance.

**Comment by pcimule** [comment]
SOLVED: dataCamp plugin not working with latest Wordpress Gutenberg editor.

Enjoy my own solution, here:

https://skylinkce.com/2020/07/11/solved-datacamp-plugin-not-working-with-latest-wordpress-gutenberg-editor/
